name: Generate my adlists

on:
  schedule:
    - cron: 0 10,22 * * *
  workflow_dispatch:

jobs:
  generate:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get -y install dos2unix
          sudo apt-get -y clean
          mkdir down dns fop nofop title checksum
          echo "MAIN_PATH=$(pwd)" >> $GITHUB_ENV
          echo "VERSION_CODE=$(date -d "8 hour" -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "MODIFY_TIME=$(date -d "8 hour" -u "+%Y/%m/%d %H:%M UTC+8")" >> $GITHUB_ENV

      - name: Download source lists
        env:
          EASY_FOP_SCRIPT: https://raw.githubusercontent.com/easylist/easylist/master/FOP.py
          MOD_FOP_SCRIPT: https://raw.githubusercontent.com/FiltersHeroes/ScriptsPlayground/master/scripts/FOP_FH.py
          EASYLIST: https://easylist-downloads.adblockplus.org/easylist.txt
          EASYLIST_NOHIDE: https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
          EASYPRIVACY: https://easylist-downloads.adblockplus.org/easyprivacy.txt
          EASYLISTCHINA: https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt
          CJX_ANNOYANCE: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          UBO_EASYLIST: https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist.txt
          UBO_EASYPRIVACY: https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/main/thirdparties/easyprivacy.txt
          UBO_EASYLISTCHINA: https://filters.adtidy.org/extension/ublock/filters/224.txt
          UBO_CJX_ANNOYANCE: https://filters.adtidy.org/extension/ublock/filters/220.txt
          MINI_EASYLIST: https://easylist-downloads.adblockplus.org/easylist-minified.txt
          MINI_EASYPRIVACY: https://easylist-downloads.adblockplus.org/easyprivacy-minified.txt
          ADGUARD_DNS: https://filters.adtidy.org/windows/filters/15_optimized.txt
          ANTI_AD_ADGUARD: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
          PETER_LOWE: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext
        run: |
          cp ${{ env.MAIN_PATH }}/material/Titles.txt ${{ env.MAIN_PATH }}/title/title.txt
          wget -qO ${{ env.MAIN_PATH }}/fop/FOP.py ${MOD_FOP_SCRIPT}
          cd ${{ env.MAIN_PATH }}/down
          wget -qO ./easylist.txt ${{ env.EASYLIST }}
          wget -qO ./easyprivacy.txt ${{ env.EASYPRIVACY }}
          wget -qO ./easylistchina.txt ${{ env.EASYLISTCHINA }}
          wget -qO ./cjx-annoyance.txt ${{ env.CJX_ANNOYANCE }}
          wget -qO ./ubo-easylist.txt ${{ env.UBO_EASYLIST }}
          wget -qO ./ubo-easyprivacy.txt ${{ env.UBO_EASYPRIVACY }}
          wget -qO ./ubo-easylistchina.txt ${{ env.UBO_EASYLISTCHINA }}
          wget -qO ./ubo-cjx-annoyance.txt ${{ env.UBO_CJX_ANNOYANCE }}
          wget -qO ./nohide-easylist.txt ${{ env.EASYLIST_NOHIDE }}
          wget -qO ./mini-easylist.txt ${{ env.MINI_EASYLIST }}
          wget -qO ./mini-easyprivacy.txt ${{ env.MINI_EASYPRIVACY }}
          wget -qO ./adgdns.txt ${{ env.ADGUARD_DNS }}
          wget -qO ./anti-ad.txt ${{ env.ANTI_AD_ADGUARD }}
          wget -qO ./peter-lowe.txt "${{ env.PETER_LOWE }}"

      - name: Preprocess
        run: |
          cd ${{ env.MAIN_PATH }}/down
          for list in ./*.txt; do
            dos2unix ./"${list}"
            echo >> ./"${list}"
          done
          cat ./adgdns.txt ./anti-ad.txt ./peter-lowe.txt | sed -e 's/\^|/\^/g' -e 's/\$important//g' -e '/^[^|@]/d' | sort -u > ../dns/dnscombined.txt
          cat ./easylist.txt ./easyprivacy.txt ./easylistchina.txt ./cjx-annoyance.txt | sed -e '/^\[Adblock/d' -e '/^!/d' | sed -E -e 's/#\?#(.*):-abp-has(.+):-abp-contains/##\1:has\2:contains/g' -e 's/#\?#(.*):-abp-has/##\1:has/g' -e 's/#\?#(.*):-abp-contains/##\1:contains/g' | sort -u > ../fop/easycombined.txt
          cat ./ubo-easylist.txt ./ubo-easyprivacy.txt ./ubo-easylistchina.txt ./ubo-cjx-annoyance.txt | sed -e '/^\[Adblock/d' -e '/^!/d' | sed -E -e 's/#\?#(.*):-abp-has(.+):-abp-contains/##\1:has\2:contains/g' -e 's/#\?#(.*):-abp-has/##\1:has/g' -e 's/#\?#(.*):-abp-contains/##\1:contains/g' | sort -u > ../fop/ubocombined.txt
          cat ./nohide-easylist.txt ./mini-easylist.txt ./mini-easyprivacy.txt ./easylistchina.txt ./cjx-annoyance.txt | sed -e '/^\[Adblock/d' -e '/^!/d' | sed -E -e 's/#\?#(.*):-abp-has(.+):-abp-contains/##\1:has\2:contains/g' -e 's/#\?#(.*):-abp-has/##\1:has/g' -e 's/#\?#(.*):-abp-contains/##\1:contains/g' | sort -u > ../fop/mobcombined.txt

      - name: Combine DNS list
        run: |
          cd ${{ env.MAIN_PATH }}/dns
          sed -i -e '/^||cis\.sohu\.com\^/d' -e '/^||t\.co\^/d' dnscombined.txt
          sed -n '/^@@/p' dnscombined.txt | sed 's/@@|/@@||/g' | sed 's/@@|||/@@||/g' | sort -u > except.txt
          sed -e '/^@@/d' -e '/[^^]$/d' -e '/\*\^/d' dnscombined.txt > common_check.txt
          grep -E '^\|\|[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level2.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level3.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level4.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level5.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level6.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level7.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level8.txt
          for ((i=2; i<=7; i++)); do
            echo -n '\S+\.(' > replace_text.txt
            for ((t=1; t<=$i-1; t++)); do
              echo -n '[^.]+\.' >> replace_text.txt
            done
            echo -n '[^.]+)' >> replace_text.txt
            replace_re=$(cat replace_text.txt)
            for ((j=$i+1; j<=8; j++)); do
              sed -E 's#^'"$replace_re"'$#\1#' level"$j".txt | sort -u > check"$i"_"$j".txt
              comm -12 level"$i".txt check"$i"_"$j".txt | sed -e 's/\./\\\./g' -e 's/\*/\\\*/g' > redun"$j"_"$i".txt
              while read redun_rule; do
                sed -i '/\.'"$redun_rule"'$/d' level"$j".txt
              done < redun"$j"_"$i".txt
            done
          done
          cat level2.txt level3.txt level4.txt level5.txt level6.txt level7.txt level8.txt | sed -n '/\*/p' > common_wildcards.txt
          cat level2.txt level3.txt level4.txt level5.txt level6.txt level7.txt level8.txt | sed '/\*/d' > common_plain.txt
          sed -e 's/\./\\\./g' -e 's/\*/\.\*/g' common_wildcards.txt > wild_check.txt
          while read wild_rule; do
            sed -Ei '/(^|\.)'"$wild_rule"'$/d' common_plain.txt
          done < wild_check.txt
          cat common_wildcards.txt common_plain.txt | sed -E 's#^(\S+)$#\|\|\1\^#' | sort > common_checked.txt
          sed 's/@@//g' except.txt > except_check.txt
          comm -13 except_check.txt common_checked.txt > common.txt
          cat except.txt common.txt | sed '/^$/d' > ${{ env.MAIN_PATH }}/title/dnsrules.txt

      - name: FOP rules
        run: |
          cd ${{ env.MAIN_PATH }}/fop
          sed -En '/^#@?#/p' easycombined.txt | sort -u > ../nofop/easy_ghide.txt
          sed -En '/^#@?#/p' ubocombined.txt | sort -u > ../nofop/ubo_ghide.txt
          sed -En '/^#@?#/p' mobcombined.txt | sort -u > ../nofop/mob_ghide.txt
          sed -Ei '/^#@?#/d' easycombined.txt
          sed -Ei '/^#@?#/d' ubocombined.txt
          sed -Ei '/^#@?#/d' mobcombined.txt
          for list in ./*.txt; do
            python ${{ env.MAIN_PATH }}/material/MDR.py ./${list}
          done
          python ./FOP.py
          cat ../nofop/easy_ghide.txt ./easycombined.txt | sed '/^$/d' > ../title/easy_done.txt
          cat ../nofop/ubo_ghide.txt ./ubocombined.txt | sed '/^$/d' > ../title/ubo_done.txt
          cat ../nofop/mob_ghide.txt ./mobcombined.txt | sed '/^$/d' > ../title/mob_done.txt

      - name: Create final lists
        run: |
          cd ${{ env.MAIN_PATH }}/title
          sed -i -e "s/BLANKVER/${{ env.VERSION_CODE }}/" -e "s#BLANKTIME#${{ env.MODIFY_TIME }}#" ./title.txt
          sed -n '/^! Title: Easy/,/^# Easy/p' title.txt | sed -e "s/NUMCOUNT/$(sed -n '$=' easy_done.txt)/" -e '/^#/d' > ./easytitle.txt
          sed -n '/^! Title: uBo Easy/,/^# uBo Easy/p' title.txt | sed -e "s/NUMCOUNT/$(sed -n '$=' ubo_done.txt)/" -e '/^#/d' > ./ubotitle.txt
          sed -n '/^! Title: Mobile/,/^# Mobile/p' title.txt | sed -e "s/NUMCOUNT/$(sed -n '$=' mob_done.txt)/" -e '/^#/d' > ./mobtitle.txt
          sed -n '/^! Title: DNS/,/^# DNS/p' title.txt | sed -e "s/NUMCOUNT/$(sed -n '$=' dnsrules.txt)/" -e '/^#/d' > ./dnstitle.txt
          cat easytitle.txt easy_done.txt > ${{ env.MAIN_PATH }}/checksum/easyrules.txt
          cat ubottitle.txt ubo_done.txt > ${{ env.MAIN_PATH }}/checksum/ubolist.txt
          cat mobtitle.txt mob_done.txt > ${{ env.MAIN_PATH }}/checksum/moblist.txt
          cat dnstitle.txt dnsrules.txt > ${{ env.MAIN_PATH }}/checksum/dnsblock.txt
          cd ${{ env.MAIN_PATH }}
          for list in ./checksum/*.txt; do
            perl ./material/addChecksum.pl ${list}
            mv -f ${list} ./
          done

      - name: Update
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add easyrules.txt ubolist.txt moblist.txt dnsblock.txt
          git commit -m "Updated on ${{ env.MODIFY_TIME }}"
          git push origin main
          [ $(date -u +%H) -gt 12 ] || curl -s https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
