name: Generate my adlists

on:
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Basic preparation
        run: |
          mkdir -p download fop ubo mod
          echo "VERSION_CODE=$(date -d "8 hour" -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "MODIFY_TIME=$(date -d "8 hour" -u "+%Y.%m.%d %H:%M UTC+8")" >> $GITHUB_ENV

      - name: Get source files
        env:
          EASYLIST: https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
          EASYLISTCHINA: https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt
          CJX_ANNOYANCE: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          ADDITION_RULES: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/Additions.txt
          EASYPRIVACY_0: https://easylist-downloads.adblockplus.org/easyprivacy_nointernational.txt
          EASYPRIVACY_1: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_allowlist_international.txt
          EASYPRIVACY_2: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_international.txt
          EASYPRIVACY_3: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_thirdparty_international.txt
          EASYPRIVACY_4: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_international.txt
          ADGUARD_DNS: https://filters.adtidy.org/windows/filters/15_optimized.txt
          ANTI_AD_ADGUARD: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
          PETER_LOWE: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext
          UBLOCK_FILTERS: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
          UBLOCK_BADWARE: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
          UBLOCK_PRIVACY: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
          UBLOCK_ABUSE: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
          UBLOCK_UNBREAK: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
          UBLOCK_QUICK: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt
          UBLOCK_2020: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
          UBLOCK_2021: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
          UBLOCK_2022: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
          FOP_SCRIPT: https://raw.githubusercontent.com/easylist/easylist/master/FOP.py
        run: |
          cd ./download
          curl -s $EASYLIST > rawad1.txt
          curl -s $EASYLISTCHINA > rawad2.txt
          curl -s $CJX_ANNOYANCE > rawad3.txt
          curl -s $ADDITION_RULES > rawad4.txt
          curl -s $EASYPRIVACY_0 > rawpri0.txt
          curl -s $EASYPRIVACY_1 > rawpri1.txt
          curl -s $EASYPRIVACY_2 > rawpri2.txt
          curl -s $EASYPRIVACY_3 > rawpri3.txt
          curl -s $EASYPRIVACY_4 > rawpri4.txt
          curl -s $FOP_SCRIPT > ../fop/FOP.py
          curl -s $ADGUARD_DNS | sed -e '/^[^|@]/d' -e '$G' > dns1.txt
          curl -s $ANTI_AD_ADGUARD | sed -e '/^!/d' -e '$G' > dns2.txt
          curl -s $PETER_LOWE | sed -e '/^!/d' -e '/^\[Adblock Plus/d' -e '$G' > dns3.txt
          cd ../ubo
          curl -s $UBLOCK_FILTERS | sed -e '/^![^#]/d' -e '/^!#include/d' -e '/^!$/d' -e '$G' > ubo1.txt
          curl -s $UBLOCK_BADWARE | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo2.txt
          curl -s $UBLOCK_PRIVACY | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo3.txt
          curl -s $UBLOCK_ABUSE | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo4.txt
          curl -s $UBLOCK_UNBREAK | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo5.txt
          curl -s $UBLOCK_QUICK | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo6.txt
          curl -s $UBLOCK_2020 | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo7.txt
          curl -s $UBLOCK_2021 | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo8.txt
          curl -s $UBLOCK_2022 | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo9.txt

      - name: Arrange addon rules
        run: |
          cd ./download
          sed -e '/^\[Adblock/d' -e '$G' rawad1.txt > ad1.txt
          sed -e '/^\[Adblock/d' -e '$G' rawad2.txt > ad2.txt
          sed -e '/^\[Adblock/d' -e '/^!#include/d' -e '$G' rawad3.txt > ad3.txt
          sed '$G' rawad4.txt > ad4.txt
          cat ad1.txt ad2.txt ad3.txt ad4.txt | sed '/^!/d' > adcombined.txt
          sed -e '/^\[Adblock/d' -e '$G' rawpri0.txt > pri0.txt
          sed -n '/^!---------- Chinese/,/^!---------- Czech/p' rawpri1.txt | sed '$G' > pri1.txt
          sed -n '/^! Chinese/,/^! Croatian/p' rawpri2.txt | sed '$G' > pri2.txt
          sed -n '/^! Chinese/,/^! Croatian/p' rawpri3.txt | sed '$G' > pri3.txt
          sed -n '/^! Chinese/,/^! Croatian/p' rawpri4.txt | sed '$G' > pri4.txt
          cat pri0.txt pri1.txt pri2.txt pri3.txt pri4.txt | sed '/^!/d' > pricombined.txt
          cat adcombined.txt pricombined.txt | sed 's/\r//g' > addonrules0.txt
          sed -n '/^\|\|[\w-]+\^$/p' addonrules0.txt | sort -u | sed '$G' > redun0.txt
          sed -n '/^\|\|[\w-]+\^\$third-party$/p' addonrules0.txt | sed '$G' > redun1.txt
          sed -n '/^\|\|[\w-]+\^\$popup$/p' addonrules0.txt | sed '$G' > redun2.txt
          sed -n '/^\|\|[\w-]+\^\$popup,third-party$/p' addonrules0.txt | sed '$G' > redun3.txt
          cat redun1.txt redun3.txt | sed 's/\$\S+//g' | sort -u > redun_3p.txt
          cat redun2.txt redun3.txt | sed 's/\$\S+//g' | sort -u > redun_pop.txt
          cat redun0.txt redun_pop.txt | sort | uniq -d > redun_temp_1.txt
          cat redun_pop.txt redun_temp_1.txt | sort | uniq -u > redun_pop1.txt
          cat redun0.txt redun_3p.txt | sort | uniq -d > redun_temp_2.txt
          cat redun_3p.txt redun_temp_2.txt | sort | uniq -u > redun_3p1.txt
          cat redun_pop1.txt redun_3p1.txt | sort | uniq -d > redun_pop_3p.txt
          cat redun_pop1.txt redun_pop_3p.txt | sort | uniq -u > redun_pop2.txt
          cat redun_3p1.txt redun_pop_3p.txt | sort | uniq -u > redun_3p2.txt
          sed 's/\^/\^\$popup,third-party/g' redun_pop_3p.txt > redun_part1.txt
          sed 's/\^/\^\$third-party/g' redun_3p2.txt > redun_part2.txt
          sed 's/\^/\^\$popup/g' redun_pop2.txt > redun_part3.txt
          cat redun0.txt redun_part1.txt redun_part2.txt redun_part3.txt > addonrules1.txt
          sed -e '/^\|\|[\w-]+\^$/d' -e '/^\|\|[\w-]+\^\$popup$/d' -e '/^\|\|[\w-]+\^\$third-party$/d' -e '/^\|\|[\w-]+\^\$popup,third-party$/d' addonrules0.txt > addonrules2.txt
          cat addonrules1.txt addonrules2.txt > ../fop/addonrules.txt
          cd ../fop
          python FOP.py
          mv addonrules.txt ../mod/addonrules.txt

      - name: Combine other rules
        run: |
          cd ./download
          cat dns1.txt dns2.txt dns3.txt | sed 's/\r//g' > ../mod/dnscombined.txt
          cd ../ubo
          cat ubo1.txt ubo2.txt ubo3.txt ubo4.txt ubo5.txt ubo6.txt ubo7.txt ubo8.txt ubo9.txt | sed 's/\r//g' > ubocombined0.txt
          sed '/^!#if/,/^!#endif/d' ubocombined0.txt > ../mod/ubocombined.txt
          sed -n '/^!#if/,/^!#endif/p' ubocombined0.txt > uboif0.txt
          sed -n '/^!#if env_chromium/,/^!#endif/p' uboif0.txt > uboifchrome0.txt
          sed -n '/^!#if env_firefox/,/^!#endif/p' uboif0.txt > uboiffire0.txt
          sed -n '/^!#if env_mobile/,/^!#endif/p' uboif0.txt > uboifmob0.txt
          sed '/^!/d' uboifchrome0.txt | sed -e '1i !#if env_chromium' -e '$a !#endif\n' > uboifchrome.txt
          sed '/^!/d' uboiffire0.txt | sed -e '1i !#if env_firefox' -e '$a !#endif\n' > uboiffire.txt
          sed '/^!/d' uboifmob0.txt | sed -e '1i !#if env_mobile' -e '$a !#endif\n' > uboifmob.txt
          sed -e '/^!#if env_chromium/,/^!#endif/d' -e '/^!#if env_firefox/,/^!#endif/d' -e '/^!#if env_mobile/,/^!#endif/d' uboif0.txt > uboifleft.txt
          cat uboifchrome.txt uboiffire.txt uboifmob.txt uboifleft.txt | sed '/^$/d' > ../mod/uboif.txt
          cd ../mod
          sort -u dnscombined.txt > dnslist.txt
          sort -u ubocombined.txt > ubolist.txt

      - name: Add titles
        env:
          ADLIST_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/AddonTitle.txt
          DNSLIST_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/DNSTitle.txt
          UBLOCK_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/uBoTitle.txt
        run: |
          cd ./mod
          curl -s $ADLIST_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > addon0.txt
          curl -s $DNSLIST_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > dns0.txt
          curl -s $UBLOCK_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > ubo0.txt
          cat addon0.txt addonrules.txt > ../addonlist.txt
          cat dns0.txt dnslist.txt > ../dnsblock.txt
          cat ubo0.txt ubolist.txt uboif.txt > ../ublocklist.txt

      - name: Commit and Purge jsDelivr
        run: |
          rm -rf download fop ubo mod
          git config user.name "actions"
          git config user.email "action@github.com"
          git add --all
          git commit -m "Updated on ${{ env.MODIFY_TIME }}"
          git push origin main
          curl -sS https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/addonlist.txt
          curl -sS https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/dnsblock.txt
          curl -sS https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/ublocklist.txt

