name: Generate my adlists

on:
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Basic preparation
        run: |
          mkdir title addon fop dns ubo
          echo "VERSION_CODE=$(date -d "8 hour" -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "MODIFY_TIME=$(date -d "8 hour" -u "+%Y/%m/%d %H:%M UTC+8")" >> $GITHUB_ENV

      - name: Get source files
        env:
          LIST_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/Titles.txt
          #FOP_SCRIPT: https://raw.githubusercontent.com/easylist/easylist/master/FOP.py
          FOP_SCRIPT: https://raw.githubusercontent.com/FiltersHeroes/ScriptsPlayground/master/scripts/FOP.py
          EASYLIST_NOHIDE: https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
          EASYLISTCHINA: https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt
          CJX_ANNOYANCE: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          ADDITION_RULES: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/Additions.txt
          EASYPRIVACY_1: https://easylist-downloads.adblockplus.org/easyprivacy_nointernational.txt
          EASYPRIVACY_2: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_allowlist_international.txt
          EASYPRIVACY_3: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_specific_international.txt
          EASYPRIVACY_4: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_thirdparty_international.txt
          EASYPRIVACY_5: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_international.txt
          ADGUARD_DNS: https://filters.adtidy.org/windows/filters/15_optimized.txt
          ANTI_AD_ADGUARD: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
          PETER_LOWE: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext
          ADAWAY_HOST: https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
          UBLOCK_FILTERS: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
          UBLOCK_2020: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
          UBLOCK_2021: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
          UBLOCK_2022: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
          UBLOCK_BADWARE: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
          UBLOCK_PRIVACY: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
          UBLOCK_ABUSE: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
          UBLOCK_UNBREAK: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
          UBLOCK_QUICK: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt
        run: |
          curl -s $LIST_TITLE > ./title/title.txt
          curl -s $FOP_SCRIPT > ./fop/FOP.py
          cd ./addon
          curl -s $EASYLIST_NOHIDE | sed '$G' > rawaddon.txt
          curl -s $EASYLISTCHINA | sed '$G' >> rawaddon.txt
          curl -s $CJX_ANNOYANCE | sed '$G' >> rawaddon.txt
          curl -s $ADDITION_RULES | sed '$G' >> rawaddon.txt
          curl -s $EASYPRIVACY_1 | sed '$G' >> rawaddon.txt
          curl -s $EASYPRIVACY_2 | sed -n '/^!---------- Chinese/,/^!---------- Czech/p' | sed '$G' >> rawaddon.txt
          curl -s $EASYPRIVACY_3 | sed -n '/^! Chinese/,/^! Croatian/p' | sed '$G' >> rawaddon.txt
          curl -s $EASYPRIVACY_4 | sed -n '/^! Chinese/,/^! Croatian/p' | sed '$G' >> rawaddon.txt
          curl -s $EASYPRIVACY_5 | sed -n '/^! Chinese/,/^! Croatian/p' | sed '$G' >> rawaddon.txt
          cd ../dns
          curl -s $ADGUARD_DNS | sed '$G' > rawdns.txt
          curl -s $ANTI_AD_ADGUARD | sed '$G' >> rawdns.txt
          curl -s $PETER_LOWE | sed '$G' >> rawdns.txt
          curl -s $ADAWAY_HOST | sed '$G' > rawhost.txt
          cd ../ubo
          curl -s $UBLOCK_FILTERS | sed -e '/^!#include/d' -e '$G' > rawubo.txt
          curl -s $UBLOCK_2020 | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_2021 | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_2022 | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_BADWARE | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_PRIVACY | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_ABUSE | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_UNBREAK | sed '$G' >> rawubo.txt
          curl -s $UBLOCK_QUICK | sed '$G' >> rawubo.txt

      - name: Combine addon lists
        run: |
          cd ./addon
          sed -e '/^\[Adblock/d' -e '/^!/d' -e 's/\r//g' rawaddon.txt | sort -u > addoncombined.txt
          sed -n '/^##/p' addoncombined.txt | sed '/ /d' > general_hide.txt
          sed -n '/+js/p' addoncombined.txt > advanced.txt
          sed -e '/^##/d' -e '/+js/d' addoncombined.txt > addon_redun_mixed.txt
          sed -n '/^||/p' addon_redun_mixed.txt > redun_raw.txt
          sed -e '/\^$/d' -e '/\^\$third-party$/d' -e '/\^\$popup$/d' -e '/\^\$popup,third-party$/d' -e '/\^\$image$/d' -e '/\^\$image,third-party$/d' \
          -e '/\^\$script$/d' -e '/\^\$script,third-party$/d' -e '/\^\$image,script$/d' -e '/\^\$image,script,third-party$/d' redun_raw.txt > redun_out.txt
          comm -13 redun_out.txt redun_raw.txt > redun_check.txt
          comm -13 redun_check.txt addon_redun_mixed.txt > addon_redun_out.txt
          sed -n '/\^$/p' redun_check.txt > addon_redun_pure.txt
          sed -n '/\^\$third-party$/p' redun_check.txt | sed 's/\$third-party//g' > redun1.txt
          sed -n '/\^\$popup$/p' redun_check.txt | sed 's/\$popup//g' > redun2.txt
          sed -n '/\^\$popup,third-party$/p' redun_check.txt | sed 's/\$popup,third-party//g' > redun3.txt
          sed -n '/\^\$image$/p' redun_check.txt | sed 's/\$image//g' > redun4.txt
          sed -n '/\^\$image,third-party$/p' redun_check.txt | sed 's/\$image,third-party//g' > redun5.txt
          sed -n '/\^\$script$/p' redun_check.txt | sed 's/\$script//g' > redun6.txt
          sed -n '/\^\$script,third-party$/p' redun_check.txt | sed 's/\$script,third-party//g' > redun7.txt
          sed -n '/\^\$image,script$/p' redun_check.txt | sed 's/\$image,script//g' > redun8.txt
          sed -n '/\^\$image,script,third-party$/p' redun_check.txt | sed 's/\$image,script,third-party//g' > redun9.txt
          cat redun1.txt redun3.txt redun5.txt redun7.txt redun9.txt | sort -u > redun_3p.txt
          cat redun2.txt redun3.txt | sort -u > redun_pop.txt
          cat redun4.txt redun5.txt redun8.txt redun9.txt | sort -u > redun_image.txt
          cat redun6.txt redun7.txt redun8.txt redun9.txt | sort -u > redun_script.txt
          comm -13 addon_redun_pure.txt redun_3p.txt > redun_3p_1.txt
          comm -13 addon_redun_pure.txt redun_pop.txt > redun_pop_1.txt
          comm -13 addon_redun_pure.txt redun_image.txt > redun_image_0.txt
          comm -13 addon_redun_pure.txt redun_script.txt > redun_script_0.txt
          comm -13 redun_image_0.txt redun_script_0.txt > redun_script_1.txt
          comm -13 redun_script_0.txt redun_image_0.txt > redun_image_1.txt
          comm -12 redun_image_0.txt redun_script_0.txt > redun_image_script_1.txt
          comm -12 redun_3p_1.txt redun_pop_1.txt > redun_3p_pop.txt
          comm -12 redun_3p_1.txt redun_script_1.txt > redun_3p_script.txt
          comm -12 redun_3p_1.txt redun_image_1.txt > redun_3p_image.txt
          comm -12 redun_3p_1.txt redun_image_script_1.txt > redun_3p_image_script.txt
          comm -13 redun_3p_1.txt redun_pop_1.txt > redun_pop_only.txt
          comm -13 redun_3p_1.txt redun_script_1.txt > redun_script_only.txt
          comm -13 redun_3p_1.txt redun_image_1.txt > redun_image_only.txt
          comm -13 redun_3p_1.txt redun_image_script_1.txt > redun_image_script_only.txt
          cat redun_3p_1.txt redun_pop_1.txt redun_image_0.txt redun_script_0.txt | sort -u > redun_passed_all.txt
          cat redun_pop_1.txt redun_image_0.txt redun_script_0.txt | sort -u > redun_passed_for3p.txt
          comm -13 redun_passed_for3p.txt redun_passed_all.txt > redun_3p_only.txt
          sed 's/\^/\^\$third-party/g' redun_3p_only.txt > addon_redun_mod.txt
          sed 's/\^/\^\$popup/g' redun_pop_only.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$popup,third-party/g' redun_3p_pop.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$image/g' redun_image_only.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$image,third-party/g' redun_3p_image.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$script/g' redun_script_only.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$script,third-party/g' redun_3p_script.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$image,script/g' redun_image_script_only.txt >> addon_redun_mod.txt
          sed 's/\^/\^\$image,script,third-party/g' redun_3p_image_script.txt >> addon_redun_mod.txt
          cat addon_redun_out.txt addon_redun_pure.txt addon_redun_mod.txt > ../fop/addon_fop.txt
          cd ../fop
          python FOP.py
          mv addon_fop.txt ../addon/addon_fopped.txt
          cd ../addon
          cat general_hide.txt addon_fopped.txt advanced.txt | sed '/^$/d' > ../title/addonrules.txt

      - name: Combine DNS lists
        run: |
          cd ./dns
          sed -e '/^#/d' -e '/localhost$/d' rawhost.txt | sed -E 's#^127\.0\.0\.1 (\S+)$#\|\|\1\^#' >> rawdns.txt
          sed -e 's/\^|/\^/g' -e 's/\$important//g' -e '/^[^|@]/d' -e 's/\r//g' rawdns.txt | sort -u > dnscombined.txt
          sed -n '/^@@/p' dnscombined.txt | sed 's/@@|/@@||/g' | sed 's/@@|||/@@||/g' | sort -u > except.txt
          sed -e '/^@@/d' -e '/[^^]$/d' -e '/\*\^/d' dnscombined.txt > common_check.txt
          grep -E '^\|\|[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level2.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level3.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level4.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level5.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level6.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level7.txt
          grep -E '^\|\|[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\^$' common_check.txt | sed -E 's#^\|\|([^^]+)\^$#\1#' > level8.txt
          for ((i=2; i<=7; i++))
          do
            echo -n '\S+\.(' > replace_text.txt
            for ((t=1; t<=$i-1; t++))
            do
              echo -n '[^.]+\.' >> replace_text.txt
            done
            echo -n '[^.]+)' >> replace_text.txt
            replace_re=$(cat replace_text.txt)
            for ((j=$i+1; j<=8; j++))
            do
              sed -E 's#^'"$replace_re"'$#\1#' level"$j".txt | sort -u > check"$i"_"$j".txt
              comm -12 level"$i".txt check"$i"_"$j".txt | sed -e 's/\./\\\./g' -e 's/\*/\\\*/g' > redun"$j"_"$i".txt
              while read redun_rule
              do
                sed -i '/\.'"$redun_rule"'$/d' level"$j".txt
              done < redun"$j"_"$i".txt
            done
          done
          cat level2.txt level3.txt level4.txt level5.txt level6.txt level7.txt level8.txt | sed -n '/\*/p' > common_wildcards.txt
          cat level2.txt level3.txt level4.txt level5.txt level6.txt level7.txt level8.txt | sed '/\*/d' > common_plain.txt
          sed -e 's/\./\\\./g' -e 's/\*/\.\*/g' common_wildcards.txt > wild_check.txt
          while read wild_rule
          do
            sed -i -E '/(^|\.)'"$wild_rule"'$/d' common_plain.txt
          done < wild_check.txt
          cat common_wildcards.txt common_plain.txt | sed -E 's#^(\S+)$#\|\|\1\^#' | sort > common_checked.txt
          sed 's/@@//g' except.txt > except_check.txt
          comm -13 except_check.txt common_checked.txt > common.txt
          cat except.txt common.txt | sed '/^$/d' > ../title/dnsrules.txt

      - name: Combine uBlock lists
        run: |
          cd ./ubo
          sed -e '/^![^#]/d' -e '/^!$/d' -e 's/\r//g' rawubo.txt > ubocombined.txt
          sed -n '/^!#if/,/^!#endif/p' ubocombined.txt > uboif0.txt
          sed -n '/^!#if env_chromium/,/^!#endif/p' uboif0.txt | sort -u > uboifchrome0.txt
          sed -n '/^!#if env_firefox/,/^!#endif/p' uboif0.txt | sort -u > uboiffire0.txt
          sed -n '/^!#if env_mobile/,/^!#endif/p' uboif0.txt | sort -u > uboifmob0.txt
          sed -n '/^!#if !env_mobile/,/^!#endif/p' uboif0.txt | sort -u > uboifnomob0.txt
          sed '/^!/d' uboifchrome0.txt | sed -e '1i !#if env_chromium' -e '$a !#endif\n' > uboifchrome.txt
          sed '/^!/d' uboiffire0.txt | sed -e '1i !#if env_firefox' -e '$a !#endif\n' > uboiffire.txt
          sed '/^!/d' uboifmob0.txt | sed -e '1i !#if env_mobile' -e '$a !#endif\n' > uboifmob.txt
          sed '/^!/d' uboifnomob0.txt | sed -e '1i !#if !env_mobile' -e '$a !#endif\n' > uboifnomob.txt
          sed -e '/^!#if env_chromium/,/^!#endif/d' -e '/^!#if env_firefox/,/^!#endif/d' \
          -e '/^!#if env_mobile/,/^!#endif/d' -e '/^!#if !env_mobile/,/^!#endif/d' uboif0.txt > uboifleft.txt
          cat uboifchrome.txt uboiffire.txt uboifmob.txt uboifnomob.txt uboifleft.txt > uboif.txt
          sed '/^!#if/,/^!#endif/d' ubocombined.txt > ../fop/ubo_fop.txt
          cd ../fop
          python FOP.py
          mv ubo_fop.txt ../ubo/ubo_fopped.txt
          cd ../ubo
          cat ubo_fopped.txt uboif.txt | sed '/^$/d' > ../title/uborules.txt

      - name: Create final lists
        run: |
          cd ./title
          addon_numcount=$(sed -n '$=' addonrules.txt)
          dns_numcount=$(sed -n '$=' dnsrules.txt)
          ubo_numcount=$(sed -n '$=' uborules.txt)
          sed -i -e "s/BLANKVER/$VERSION_CODE/" -e "s#BLANKTIME#$MODIFY_TIME#" title.txt
          sed -n '/^! Title: AdList/,/^# Addon/p' title.txt | sed -e "s/NUMCOUNT/$addon_numcount/" -e '/^#/d' > addontitle.txt
          sed -n '/^! Title: DNS/,/^# DNS/p' title.txt | sed -e "s/NUMCOUNT/$dns_numcount/" -e '/^#/d' > dnstitle.txt
          sed -n '/^! Title: uBlock/,/^# uBo/p' title.txt | sed -e "s/NUMCOUNT/$ubo_numcount/" -e '/^#/d' > ubotitle.txt
          cat addontitle.txt addonrules.txt > ../addonlist.txt
          cat dnstitle.txt dnsrules.txt > ../dnsblock.txt
          cat ubotitle.txt uborules.txt > ../ublocklist.txt
          cd ..
          rm -rf title addon fop dns ubo

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add addonlist.txt dnsblock.txt ublocklist.txt
          git commit -m "Updated on $MODIFY_TIME"
          git push origin main

      - name: Purge jsDelivr
        run: |
          curl -sS https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/addonlist.txt
          curl -sS https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/dnsblock.txt
          curl -sS https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/ublocklist.txt
