name: Generate my adlists
on:
  schedule:
    - cron: 0 10/12 * * *
  push:
    branches:
      - "main"
jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Combine source lists
        env:
          EASYLIST_NOHIDE: https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt
          EASYPRIVACY: https://easylist-downloads.adblockplus.org/easyprivacy.txt
          ADGUARDCHINESE: https://filters.adtidy.org/extension/ublock/filters/224_optimized.txt
          CJX_ANNOYANCE: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          ADDITION_RULES: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/Additions.txt
          ADGUARD_DNS: https://filters.adtidy.org/windows/filters/15_optimized.txt
          PETER_LOWE: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext
          ANTI_AD_ADGUARD: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
          ANTI_AD_EASYLIST: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
          UBLOCK_FILTERS: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
          UBLOCK_BADWARE: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
          UBLOCK_PRIVACY: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
          UBLOCK_RESOURCE_ABUSE: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
          UBLOCK_UNBREAK: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
          UBLOCK_2020: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
          UBLOCK_2021: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
          UBLOCK_2022: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
        run: |
          mkdir -p mod download
          cd ./download
          curl -s $EASYLIST_NOHIDE | sed -e '/^!/d' -e '/^\[Adblock Plus/d' -e '$G' > ad1.txt
          curl -s $EASYPRIVACY | sed -e '/^!/d' -e '/^\[Adblock Plus/d' -e '$G' > ad2.txt
          curl -s $ADGUARDCHINESE | sed -e '/^!/d' -e '$G' > ad3.txt
          curl -s $CJX_ANNOYANCE | sed -e '/^!/d' -e '/^\[Adblock Plus/d' -e '/^!#include/d' -e '$G' > ad4.txt
          curl -s $ADDITION_RULES | sed -e '/^!/d' -e '$G' > ad5.txt
          curl -s $ADGUARD_DNS | sed -e '/^!/d' -e '$G' > agdns.txt
          curl -s $PETER_LOWE | sed -e '/^!/d' -e '/^\[Adblock Plus/d' -e '$G' > pldns.txt
          curl -s $ANTI_AD_ADGUARD | sed -e '/^!/d' -e '$G' > dns2.txt
          curl -s $ANTI_AD_EASYLIST | sed -e '/^!/d' -e '$G' > agh2.txt
          curl -s $UBLOCK_FILTERS | sed -e '/^![^#]/d' -e '/^!#include/d' -e '/^!$/d' -e '$G' > ubo1.txt
          curl -s $UBLOCK_BADWARE | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo2.txt
          curl -s $UBLOCK_PRIVACY | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo3.txt
          curl -s $UBLOCK_RESOURCE_ABUSE | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo4.txt
          curl -s $UBLOCK_UNBREAK | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo5.txt
          curl -s $UBLOCK_2020 | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo6.txt
          curl -s $UBLOCK_2021 | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo7.txt
          curl -s $UBLOCK_2022 | sed -e '/^![^#]/d' -e '/^!$/d' -e '$G' > ubo8.txt
          cat ad1.txt ad2.txt ad3.txt ad4.txt ad5.txt > adcombined0.txt
          cat agdns.txt pldns.txt dns2.txt > dnscombined0.txt
          cat agdns.txt pldns.txt agh2.txt > aghcombined0.txt
          cat ubo1.txt ubo2.txt ubo3.txt ubo4.txt ubo5.txt ubo6.txt ubo7.txt ubo8.txt > ubocombined1.txt
          sed -n '/^!#if/,/^!#endif/p' ubocombined1.txt > uboif0.txt
          sed -e '/^!#if/,/^!#endif/d' ubocombined1.txt > ubocombined0.txt
          sed 's/\r//g' adcombined0.txt > adcombined.txt
          sed 's/\r//g' dnscombined0.txt > dnscombined.txt
          sed 's/\r//g' aghcombined0.txt > aghcombined.txt
          sed 's/\r//g' ubocombined0.txt > ubocombined.txt
          sed -e 's/\r//g' -e '/^$/d' uboif0.txt > ../mod/uboif.txt
          sort -u adcombined.txt > ../mod/adlist.txt
          sort -u dnscombined.txt > ../mod/dnslist.txt
          sort -u aghcombined.txt > ../mod/aghlist.txt
          sort -u ubocombined.txt > ../mod/ubolist.txt

      - name: Generate titles and final lists
        env:
          ADLIST_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/AddonTitle.txt
          DNSLIST_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/DNSTitle.txt
          AGHLIST_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/AGHTitle.txt
          UBLOCK_TITLE: https://raw.githubusercontent.com/MkQtS/MyAdList/main/material/uBoTitle.txt
        run: |
          echo "VERSION_CODE=$(date -d "8 hour" -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "MODIFY_TIME=$(date -d "8 hour" -u "+%Y.%m.%d %H:%M UTC+8")" >> $GITHUB_ENV
          cd ./mod
          curl -s $ADLIST_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > ad0.txt
          curl -s $DNSLIST_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > dns0.txt
          curl -s $AGHLIST_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > agh0.txt
          curl -s $UBLOCK_TITLE | sed -e "s/BLANKVER/$VERSION_CODE/" -e "s/BLANKTIME/$MODIFY_TIME/" > ubo0.txt
          cat ad0.txt adlist.txt > ../addonlist.txt
          cat dns0.txt dnslist.txt > ../dnsblock.txt
          cat agh0.txt aghlist.txt > ../adguardhome.txt
          cat ubo0.txt uboif.txt ubolist.txt > ../ublocklist.txt
          cd ..
          rm -rf ./download ./mod

      - name: Commit and Purge jsdelivr cache
        run: |
          git config user.name "actions"
          git config user.email "action@github.com"
          git add --all
          git commit -m "Updated on ${{ env.MODIFY_TIME }}"
          git push origin main
          curl -s https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/addonlist.txt
          curl -s https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/dnsblock.txt
          curl -s https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/adguardhome.txt
          curl -s https://purge.jsdelivr.net/gh/MkQtS/MyAdList@main/ublocklist.txt
